apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: internal-services
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: internal-services
    app.kubernetes.io/part-of: internal-services
  name: internal-services
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: internal-services
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: internal-services
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/internal-services/internal-services@sha256:c193be48e32fca49c0638b78d7f8130adf1f8c0a61624afc07574257f624e14d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
