apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: internal-services
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/internal-services/internal-services@sha256:4724939308092598d811aa89a5723b3aea4023ee79c8820832c920fc381ea776
        name: container-image
        resources: {}
status: {}
