apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: internal-services
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/internal-services/internal-services@sha256:2066bb77d19d149c57ab54dcd1e39b9b427e2d7ba85dc921448b59f855bc9d2e
        name: container-image
        resources: {}
status: {}
