apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: internal-services
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/internal-services/internal-services@sha256:373eda328f94636dfb9ec384ac3418a104505bc80b454657cf145aca97cbc3cf
        name: container-image
        resources: {}
status: {}
