apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: internal-services
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/internal-services/internal-services@sha256:8436eae6aa4963f4c69019c6a6f13eabe90cd9bbb5416b4b2c21449bc74195db
        name: container-image
        resources: {}
status: {}
